language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-darty
    - secure: "ps+VU4aOVV8CnxKsCaV2Weffh/inLYgUz11Sfay97cC+EUvfSOvifLINAi7U57gbCzu9bRkbRYxTDMxyPxYyS/pmSCOMdPP9YWeI/E6WKHykIJ+Zdfk4n9Mx2nt6WBDEqAkQDSz9ueSnFv5cT68ysT+vjXelZDnQ37M5JwZM2B2NeozIVY0n6cR0Bhk4Nlx51cqVr7oFh3WSKua+eBrf4+wWHuZ9wu3ogjzJuGEXv1RUQytzUBlxCAM8Ot2i/L7FyWkP1+oZEVZenmAtG0DWxJd5+gyUud46kAc2i5FAIvXhwdCoQfOElGhjrDK/X1s9ob4GgMv7/P9Q8bN4xp1d/JCLTUpVfei6csyst6r3Ukp8eIN3fbds5TkwteIk0Jhf0QaiFMXQLdlYxewlq8CrhmkT/L6jdkZj47a9y+n9x3wEmVIhjVq4b1bOjalbZHzRdSNy6hCcIuzmm2GFGlAuGPaXuecH2k6kQkIAQUpIcLbEul0q6OVVDjv5RqydTQj2GPE3RLhX8CP1EiOXYrz3qEiQ34/qS/EohaiGRzgfH4bIwZ4gUXw0g4NZXut5MPd1dUKroJ1+Piu/stXk7pHJqOFD8+n63a8GioOXQJVm/J8UqY7yYwOqbJWg9Ete5ULrykCSh7buOmhWuh/eCGQUCz0x5sPmy+FRQLnnZWdN7lE="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-darty
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-darty
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
